### ISSUE TITLE
Sending bundles to supercollider - timetag may be incorrect

### ISSUE THREAD

**Issue by crucialfelix** [russellmcc/node-osc-min#11]
Hi, I've been using osc-min for formatting OSC messages for quite some time, but never used it for bundles.

Sorry to be a bit vague, but it doesn't seem to work. I'm just checking if you have used bundle sending or know of anyone who has.

```
// this is sending a message
sendosc: {
             "address": "/g_new",
             "args": [
               1000,
               0,
               0
             ]
           }
// supercollider responds
rcvosc : [
             "/n_go",
             1000,
             0,
             -1,
             -1,
             1,
             -1,
             -1
           ]
1000 { parent: 0,
  previous: -1,
  next: -1,
  isGroup: true,
  head: -1,
  tail: -1,
  isPlaying: true,
  isRunning: true }

// this is sending a bundle. this is what is passed to osc.toBuffer
sendosc: {
             "oscType": "bundle",
             "timetag": 1450714988704,
             "elements": [
               {
                 "address": "/g_new",
                 "args": [
                   1001,
                   0,
                   0
                 ]
               }
             ]
           }
```

no response. 

```
        var buf = osc.toBuffer(bundle);
        socket.send(buf, 0, buf.length, this.options.serverPort, this.options.host);
```

I've checked through your code quite a bit. 

It may be something to do with the timetag

    oscTimeTag = exports.toIntegerBuffer timetag, "UInt64"

I think this should be pushed as two Int32 - one is the seconds since epoch, the other is the fractional seconds (picoseconds)

**Comment by russellmcc** [comment]
Hey!  Thanks for digging into this a little bit.  This time of year is pretty hectic for me, so it may be a few days before I can take a look.

**Comment by crucialfelix** [comment]
Yep, totally hectic. But today I indulged myself by having a hack on something.

I'm pretty certain I'm right about this. I compared with osc.js. 

I'll put together a fix and PR for this

**Comment by russellmcc** [comment]
That would be awesome, thanks!
