### ISSUE TITLE
Big JavaScript numbers are not handled well

### ISSUE THREAD

**Issue by sebpiq** [russellmcc/node-osc-min#16]
This has to do with JavaScript numbers being encoded to Float32.

``` javascript
var oscMin = require('osc-min')
  , original = 2147483643
  , data, decoded

data = oscMin.toBuffer({ address: '/', args: [original] })
decoded = oscMin.fromBuffer(data)
console.log(decoded.args[0].value) // -> 2147483648
```

I am not sure how this should be handled, whether double should be used automatically when number is too big (but double is not standard right?) or whether an error should be thrown, but in any case I don't think it should silently encode the number with a precision that is much too low ...

**Comment by russellmcc** [comment]
Yeah, good point.  I don't have a great answer here, since as you say we can't just arbitrarily change the types.  Perhaps in strict mode we can throw an error if the number couldn't be encoded in the given types?

**Comment by sebpiq** [comment]
I think it would be find to arbitrarily change the types, since you are mapping a JS type to an OSC one. I don't see a problem in conditionally choosing a different OSC type depending on the size of the number. What is a problem though is if those types are not standards ...
Throwing an error might be a good compromise ...

**Comment by russellmcc** [comment]
closing this due to age... I feel like it's hard to know what to do here, `float` is the more standard type, and silent truncation actually seems okay as a behavior here to me.  you can explicitly set the type to `double` if you need to pass a big number
