### ISSUE TITLE
TypeScript support ?

### ISSUE THREAD

**Issue by EMCP** [russellmcc/node-osc-min#18]
I am playing with TypeScript, and including this module in some work.. noticed that the following command came back empty

`npm install @types/osc-min`

is there a way I can help with this?  I am quite new to typescript but the compiler/transpiler seems to want this type definitions added somehow.  Thank you!

**Comment by russellmcc** [comment]
Hi!  Thanks for the note!  Currently, this project does not support typescript.  As you can probably tell, it was written some time ago in coffee script.  As I understand it (and I'm not an expert either), the easiest way to add support for TypeScript is to add a declaration file.  There's a section on declaration files in the [TypeScript handbook](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)

Unfortunately, I don't have too much time to devote to this at the moment but I'd gladly review a PR.  I'd also be able to help with any specific questions that come up.  I'd be really excited to add support for typescript.

**Comment by EMCP** [comment]
I actually noticed the only thing I needed to port, was the Buffer related work.. so I simply can switch to the native Buffer call, instead of leveraging `osc-min`

https://github.com/alpacaaa/max4node/blob/master/max4node.js#L57

```
      obj = osc.fromBuffer(msg);
```

now becomes 

```
        var buf = Buffer.from(JSON.stringify({
            response_address: '/' + address, 
            payload: msg
        }));
```

I will give that a try and if not, surely will attempt to PR this and continue using `osc-min`

tacks for the quick response

**Comment by EMCP** [comment]
Now I understand there is a message format.  Will see about fixing this issue then for the library

**Comment by oveddan** [comment]
It would be great if this lib had typescript support.  Especially for those new to OSC - you'd be able to see all what is possible to send in a message, and the valid formats.

**Comment by russellmcc** [comment]
I agree that this would be a great feature!  Really hoping someone opens a PR - let me know if you have specific questions on how to get going.  Unfortunately I don't think I'll have the time to do this in in the near future.
