### ISSUE TITLE
Support for non-standard type tags

### ISSUE THREAD

**Issue by MylesBorins** [russellmcc/node-osc-min#19]
The [osc spec](https://hangar.org/wp-content/uploads/2012/01/The-Open-Sound-Control-1.0-Specification-opensoundcontrol.org_.pdf) identifies a number of "non-standard" type tags including `c`

I've recently switched to using node-osc-min for decoding OSC messages in node-osc and received a bug report about missing support for the `c` type tag. Would you be open to adding some of these non-standard types? (I think `t` is a non-standard type which is already included)

edit: to clarify I'd be up to help with implementation, just want to make sure there would be interest in the implementation if were going to do the work

**Comment by benoitlahoz** [comment]
I know this is a bit old, but I would be very interested in an implementation of the 'r' (color) type tag, used in [VDMX](https://vidvox.net/) for example, which would allow passing color values between apps.

For the time being it is throwing an error.

**Comment by russellmcc** [comment]
Hey, thanks for the comment and sorry for the late response - as you can probably guess, this project is in maintenance mode and I haven't had a lot of time to work on it.  The tooling is a bit out of date as we're still using coffeescript 👀...  I'd welcome any PRs in the meantime but no promises I'll update this soon, sorry!

**Comment by russellmcc** [comment]
Since there were a few other issues posted in this repo, I ported to typescript and implemented these types!  There's a few breaking changes in the API, lmk if you have any trouble moving to the new version.
