### ISSUE TITLE
Possible regression from 1.x to 2.x with the introduction of DataView

### ISSUE THREAD

**Issue by MylesBorins** [russellmcc/node-osc-min#25]
It seems like the underlying data representation used within osc-min is now a DataView, and that structure gets lost when sending an encoded buffer over udp via Node.js's internal dgram lib.

Below is a minimal reproduction using only `osc-min` and Node.js built ins. The sample works fine with osc-min@1 but breaks with osc-min@2.

It's possible there is just a small amount of data management that needs to happen in the client to account for this, but considering most OSC libraries will be likely leveraging `dgram` to send / receive message this feels like a non-trivial regression that will require bespoke code in most implementations to accommodate.

Please lmk if you have any pointers thanks!

```js
import { createSocket } from 'node:dgram';
import { fromBuffer, toBuffer } from 'osc-min';

const PORT = '3030';
const HOST = '127.0.0.1';

const client = createSocket({
    type: 'udp4',
    reuseAddr: true
});

const server = createSocket({
    type: 'udp4',
    reuseAddr: true
});

server.bind(3030, '127.0.0.1');

server.on('listening', () => {
    const mes = {
        address: '/hello',
        args: [ { type: 'string', value: 'world' } ],
        oscType: 'message'
    };
    const buf = toBuffer(mes);
    client.send(buf, 0, buf.length, PORT, HOST);
});

server.on('message', (msg) => {
    client.close();
    const decoded = fromBuffer(msg);
    console.log(decoded);
    server.close();
});

```

**Comment by russellmcc** [comment]
Hey, thanks for trying out version 2!

I think the issue with the above example is that you're sending `buf.length` to `client.send`, but `DataView` actually doesn't have a `length` property, it's called `byteLength` - could you try changing that to `buf.byteLength`? I think it should work.  Sorry about the trouble here.

**Comment by MylesBorins** [comment]
OK... that fixes this one :D

There are some other edge cases I'm running into. I'll open issue as I stumble across more things w/o being able to find a fix. Thanks for the quick response.
