### ISSUE TITLE
Export more types

### ISSUE THREAD

**Issue by jwetzell** [russellmcc/node-osc-min#27]
When using in typescript it would be nice to be able to use certain types from inside `osc-utilities` mainly those that `toBuffer` and `fromBuffer` reference. 

Something like the below in `index.ts` unless I'm missing some way to get at these types.

`export { type OscPacketOutput } from './osc-utilities.js'`

**Comment by russellmcc** [comment]
Hey, good call, just published 2.1.0 with some types, lmk if this works for you

**Comment by russellmcc** [comment]
Thanks for the report!

**Comment by jwetzell** [comment]
@russellmcc from what I can see v2.1.0 and v2.0.0 are identical except for the version in the package.json

<img width="584" alt="Screenshot 2024-10-27 at 1 28 48 PM" src="https://github.com/user-attachments/assets/75584d16-000c-40aa-85b4-15fe3cca27ee">

**Comment by russellmcc** [comment]
Hey, I think something went wrong with the publish, sorry. 2.1.1 should [have these types](https://www.npmjs.com/package/osc-min?activeTab=code)!

**Comment by jwetzell** [comment]
Got it now! Thanks @russellmcc
